// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrPNnigq-yTQzdzNF72E0IhUTZw6-5UMQ',
    appId: '1:166905818362:web:d602410dab996afe18ad43',
    messagingSenderId: '166905818362',
    projectId: 'com-example-angelaapp-99a81',
    authDomain: 'com-example-angelaapp-99a81.firebaseapp.com',
    storageBucket: 'com-example-angelaapp-99a81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWo9fB-E3ggAkwJm2x2COff568Kpya5vk',
    appId: '1:166905818362:android:c10760c66bdc4e5018ad43',
    messagingSenderId: '166905818362',
    projectId: 'com-example-angelaapp-99a81',
    storageBucket: 'com-example-angelaapp-99a81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCecHrzy5khsT-dhRTrop-v_Dd6QYkk3t4',
    appId: '1:166905818362:ios:c5976fdab3d7242e18ad43',
    messagingSenderId: '166905818362',
    projectId: 'com-example-angelaapp-99a81',
    storageBucket: 'com-example-angelaapp-99a81.firebasestorage.app',
    iosBundleId: 'com.example.angelaCoroV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCecHrzy5khsT-dhRTrop-v_Dd6QYkk3t4',
    appId: '1:166905818362:ios:c5976fdab3d7242e18ad43',
    messagingSenderId: '166905818362',
    projectId: 'com-example-angelaapp-99a81',
    storageBucket: 'com-example-angelaapp-99a81.firebasestorage.app',
    iosBundleId: 'com.example.angelaCoroV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrPNnigq-yTQzdzNF72E0IhUTZw6-5UMQ',
    appId: '1:166905818362:web:9f28189a7b2cfe3218ad43',
    messagingSenderId: '166905818362',
    projectId: 'com-example-angelaapp-99a81',
    authDomain: 'com-example-angelaapp-99a81.firebaseapp.com',
    storageBucket: 'com-example-angelaapp-99a81.firebasestorage.app',
  );
}
